### ISSUE TITLE
Fails to compile with eslint-plugin-react@7.25.0

### ISSUE THREAD

**Issue by bathtaters** [ezhlobo/eslint-plugin-react-pug#81]
Throws compiling error: utils.getReturnPropertyAndNode is not a function occurred while linting

getReturnPropertyAndNode was removed from eslint-plugin-react/lib/util/Components.js in v7.25
Forcing eslint-plugin-react@7.24.0 fixes this.

**Comment by ezhlobo** [comment]
Thank you for pointing that out.

**Comment by aspiiire** [comment]
Thanks @bathtaters for the solution @ezhlobo  Could you please add some sort of error to allow people to understand that they should add a previous version of plugin-react? I lost so much time trying to figure out what was the problem

**Comment by ezhlobo** [comment]
@aspiiire I feel you and apologise. My intention was to set it up working with new react but then I lost in time. I would definitely like to ship an update to README with warning here.
